spring.application.name=Script Writer
spring.datasource.url=jdbc:postgresql://localhost:5432/company_db
spring.datasource.username=shivam
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.refreshExpirationMs = 604800000

app.bootstrap-admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap-admin.name=${APP_BOOTSTRAP_ADMIN_NAME:}
app.bootstrap-admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:}
app.bootstrap-admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:}
